name: Release
on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          config-file: release-please-config.json
          manifest-file: .release-please-manifest.json

      - name: Checkout code
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/checkout@v4

      - name: Setup Node/Bun for Publishing
        if: ${{ steps.release.outputs.releases_created }}
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          registry-url: 'https://npm.pkg.github.com'
          scope: '@blackwh1te'

      - name: Install and Build
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          npm install -g bun
          bun install
          bun run build

      - name: Generate SBOM
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          npm i -g @cyclonedx/cyclonedx-npm
          cyclonedx-npm --output-format JSON --output-file sbom.json
          
      - name: Generate Checksums
        if: ${{ steps.release.outputs.releases_created }}
        run: |
          sha256sum sbom.json > checksums.txt
          
      - name: Upload Artifacts to Release
        if: ${{ steps.release.outputs.releases_created }}
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.release.outputs.tag_name }}
          files: |
            sbom.json
            checksums.txt

      - name: Publish Packages
        if: ${{ steps.release.outputs.releases_created }}
        run: npm publish --workspaces --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
